### ISSUE TITLE
Rebinder calls Spring Boot's BPP in a totally different lifecyle

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-commons#177]
`ConfigurationPropertiesRebinder` calls a  `BeanPostProcessor` itself outside of the lifecycle for which is is defined. `ConfigurationPropertiesBindingPostProcessor#postProcessBeforeInitialization` is not meant to be called directly, it is a `BeanPostProcessor` callback. 

The side effect is that, while in a valid `BPP`, we'll get the raw bean since the proxies won't have been created yet. Spring Cloud is calling the same method with the actual bean that can be proxied.

Consider the following example:

```java
@ConfigurationProperties("foo")
@Validated
public class SampleProperties {

	@NotNull(message = "That should not be null")
	private String name;

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
}
```

If you try to define such configuration with Spring Cloud, That code in `ConfigurationPropertiesRebinder` passes a proxy (because of `@Validated`). Hibernate Validator applies the validation on the proxy, the fields are all null:

```
Caused by: org.springframework.validation.BindException: org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanPropertyBindingResult: 1 errors
Field error in object 'foo' on field 'name': rejected value [null]; codes [NotNull.foo.name,NotNull.name,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [foo.name,name]; arguments []; default message [name]]; default message [That should not be null]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.checkForBindingErrors(PropertiesConfigurationFactory.java:359) ~[spring-boot-1.5.2.BUILD-SNAPSHOT.jar:1.5.2.BUILD-SNAPSHOT]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:276) ~[spring-boot-1.5.2.BUILD-SNAPSHOT.jar:1.5.2.BUILD-SNAPSHOT]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:240) ~[spring-boot-1.5.2.BUILD-SNAPSHOT.jar:1.5.2.BUILD-SNAPSHOT]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:329) ~[spring-boot-1.5.2.BUILD-SNAPSHOT.jar:1.5.2.BUILD-SNAPSHOT]
	... 47 common frames omitted
```

If you move the constraint to the getter, that exact same use case will work.

There is a sample that reproduces this issue [here](https://github.com/spring-projects/spring-boot-issues/tree/master/gh-8173)

**Comment by marcingrzejszczak** [comment]
Related to https://github.com/spring-cloud/spring-cloud-commons/issues/175

**Comment by snicoll** [comment]
See https://github.com/spring-projects/spring-boot/issues/8173#issuecomment-279748731 - On a related note, if you need a public API to bind a `ConfigurationProperties` object, please ask for it and do not call our BPP directly.

**Comment by spencergibb** [comment]
See https://github.com/spring-projects/spring-boot/issues/8344

**Comment by jonathanborenstein** [comment]
Does this have anything to do with https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinder.java#L105 calling postProcessBeforeInitialization(bean, name) on the binder object, instead of calling https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/context/properties/ConfigurationPropertiesBeans.java#L84 which is also a postProcessBeforeInitialization method?

**Comment by dsyer** [comment]
Well sort of. But "instead of" doesn't make much sense (the two BPP do quite different things).

**Comment by spencergibb** [comment]
@dsyer did 8347c5741c3100a5f941db32f43f5088bb54bad5 take care of this for the short term while we wait on https://github.com/spring-projects/spring-boot/issues/8344?

**Comment by dsyer** [comment]
Yes

**Comment by sebastiankirsch** [comment]
@dsyer So we've upgraded to spring-cloud-commons:1.1.8.RELEASE, but we still run into this problem. Is that expected behavior or did we miss a part of the workaround?

**Comment by dsyer** [comment]
1.1.8 has that fix. What exactly is the problem? Do you have a sample project?

**Comment by sebastiankirsch** [comment]
Our problem is attributes in @ConfigurationProperties being set both explicitly and by default, but still not being "available" for validation (as in the original issue report), hence startup fails.

We have a Boot 1.5.2 application using an internal library with some @ConfigurationProperties, so we see the WARNs about the deprecation.
We added @Validated to the @ConfigurationProperties in the internal library; but when we use the new library version with the change we run into this problem. Unfortunately this isn't something I can share. Maybe we can extract a sample project, but this will take us a while.

**Comment by dsyer** [comment]
A sample project will certainly help. Also there were some validation issues in Spring Boot (and I'm not sure they were fixed in 1.5.3), so it's worth checking again with snapshots.

**Comment by sebastiankirsch** [comment]
@dsyer here you go: https://github.com/sebastiankirsch/spring-cloud-commons-177

We "fixed" the issue by moving the `@Validated` annotation to the getter instead.
In the meantime, we're also rolling with the latest `spring-cloud-starter-config` version (1.3.0.RELEASE), which seems to work with annotations at the field level.

By playing around with the used version for `spring-cloud-commons` in the parent pom, I found that no released version fixes this issue. So there's probably something else that caused this behavior.

**Comment by JeffQuandt** [comment]
Any update on this? I'm running into this issue on the autoconfigured DataSource bean. Using spring-cloud-commons-1.2.2.RELEASE and Spring Boot 1.5.2.RELEASE. 

Debugging shows I'm getting a `com.sun.proxy.$Proxy` for the DataSource, even with `spring.aop.proxy-target-class=true`.

```
java.lang.NullPointerException: null
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor$ValidatedLocalValidatorFactoryBean.supports(ConfigurationPropertiesBindingPostProcessor.java:423) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.determineValidator(ConfigurationPropertiesBindingPostProcessor.java:353) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:314) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:296) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:105) ~[spring-cloud-context-1.2.2.RELEASE.jar:1.2.2.RELEASE]
```

**Comment by dsyer** [comment]
Please try the latest versions.

**Comment by Sangdol** [comment]
This is still happening with Spring Boot 1.5.6.RELEASE and Spring Cloud Commons 1.2.3.RELEASE.

**Comment by dsyer** [comment]
As far as we know the original issue has been worked round in latest versions. If you believe otherwise, you'll have to provide more information (e.g. a sample project).
