### ISSUE TITLE
No autoconfigured MessageSource with bootstrap context

### ISSUE THREAD

**Issue by willtran-** [spring-cloud/spring-cloud-commons#29]
MessageSourceAutoConfiguration is @ConditionalOnMissingBean(MessageSource.class), but the BootstrapApplicationListener kicks in and org.springframework.context.support.AbstractApplicationContext.initMessageSource() is called before the MessageSourceAutoConfiguration. This creates a DelegatingMessageSource that points nowhere

See
https://github.com/spring-projects/spring-boot/blob/v1.2.3.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/MessageSourceAutoConfiguration.java#L53 and https://github.com/spring-projects/spring-framework/blob/v4.1.6.RELEASE/spring-context/src/main/java/org/springframework/context/support/AbstractApplicationContext.java#L622

**Comment by willtran-** [comment]
See https://github.com/willtran-/spring-cloud-commons-issues-29 for a test

**Comment by dsyer** [comment]
This is fixed in Spring Boot 1.2.6 and 1.3.0. Nothing we can do here as far as I can tell.

**Comment by spencergibb** [comment]
@dsyer https://github.com/spring-cloud/spring-cloud-config/issues/217 was reported and I didn't see this issue before I started investigating.  I got the sample running with 1.2.6.BUILD-SNAPSHOT (to tell the reporter it was fixed) and still see this problem.

**Comment by spencergibb** [comment]
@dsyer it does work in 1.3.0.BUILD-SNAPSHOT
